siteName = "HRocket"
theme = "HR_Bootstrap"
disqusShortname = ""
BuilPath = "/var/www/static_site.com/public"


[[mainMenu]]
  name = "GitHub"
  url = "https://github.com/"
[[mainMenu]]
  name = "Linkedin"
  url = "https://www.linkedin.com/"
[[mainMenu]]
  name = "Twitter"
  url = "https://twitter.com/"
[[mainMenu]]
  name = "About"
  url = "/content/pages/about"
[[mainMenu]]
  name = "Blogs"
  url = "/content/pages/blogs"


[params]
    description = ""
    [params.logo]
      url = "logo.svg"
      width = 50
      height = 50
      alt = "Logo"
    [params.favIcon]
      url = "favicon.ico"

