siteName = "HRocket"
theme = "HR_Publisher"
disqusShortname = ""
BuilPath = "/var/www/static_site.com/public"
publishDir = ""
logoLink = "/"
metaKeywords = "HTML, CSS, XML, XHTML, JavaScript"
googleAnalyticsTrackingId = "UA-232232-34"
siteUrl = "http://example.com"
robotsAllow = "False"

[[mainMenu]]
  name = "Home"
  url = "/"
[[mainMenu]]
  name = "About"
  url = "/content/pages/about"
[[mainMenu]]
  name = "Blogs"
  url = "/content/pages/blogs"


[params]
    description = ""
    [params.logo]
      url = "logo.png"
      width = 50
      height = 50
      alt = "Logo"
    [params.favIcon]
      url = "favicon.ico"

